
default: &default
  adapter: postgresql
  pool: 5
  host: localhost
  username: messageboarddbuser
  password: password

development:
  <<: *default
  database: messageboarddevelopment

test:
  <<: *default
  database: messageboardtest

production:
  <<: *default
  database: messageboardproduction
