# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57aaebeb011ce2f7470ae60623044e817ce7297abba41084b1f4d094316f313bab8e3b327e83368b38c4509980defd7ff3d25f1c854cf359992333efc008479a

test:
  secret_key_base: 43905f70da85323387263b4be0e148a7edfe60bc8763540171355e9e6f1994fd6e2c5d9d1772ad53e958559d2cf81f89c0665daa26d7875e130616645e490479

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
